kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: compile
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
    - sh build.sh
- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
    - sh test.sh
